### ISSUE TITLE
The Call Timer Needs To Chill

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#10]
Hey, I appreciate the effort towards this project. I love the UI and I can't wait to see it function as everyone expected. 👍

Btw,  while making calls with it, I noticed that the call timer counts even before the other party picks up the call. Was this intended?

Thank you.

**Comment by roeiedri** [comment]
First of all we are overwhelmed with you help and effort and thank you.The timer does work like that, you can use the timer to answer or reject even before the call starts. I hope that answers your question Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: solomon stephen <notifications@github.com> Date: 5/16/19  14:09  (GMT+02:00) To: Chooloo/call_manage <call_manage@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Chooloo/call_manage] The Call Timer Needs To Chill (#10) Hey, I appreciate the effort towards this project. I love the UI and I can't wait to see it function as everyone expected. 👍

Btw,  while making calls with it, I noticed that the call timer counts even before the other party picks up the call. Was this intended?

Thank you.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Chooloo/call_manage/issues/10?email_source=notifications\u0026email_token=AF574R3X5HBIXY4GLQTC443PVU6H3A5CNFSM4HNLOSE2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUERYFA",

"url": "https://github.com/Chooloo/call_manage/issues/10?email_source=notifications\u0026email_token=AF574R3X5HBIXY4GLQTC443PVU6H3A5CNFSM4HNLOSE2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUERYFA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by realrufans** [comment]
Yeah thanks
