### ISSUE TITLE
The [call_manage ] application does not appear when I click the google play store button

### ISSUE THREAD

**Issue by XAMIR555** [Chooloo/call_manage#12]
#### Project Information
* Repository-----------:[Here](https://github.com/Chooloo/call_manage)
* Project Name---------: call_manage
* Publisher------------:  [Chooloo](https://github.com/Chooloo)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I click on the Google Play Store button, The Call-manage application should appear in the Google Play Store so that from where I install this application in my mobile

#### Actual behavior

When I click the Google Play Store button, the application does not appear further, but there is an error in which it is written (no app such found)

#### How to reproduce
* Open [github ](https://github.com/Chooloo/call_manage)link on mobile 
* Click the Google Play Store button

* Note the Bug

* Operating system----: 9.0.0

#### Recording Of The Bug
![20190517_014318.gif](https://ipfs.busy.org/ipfs/QmcrvWhiBSJMMRtw4B6nCBQBRgbzM3u9p4XXrAPwKp4BKt)

**Comment by roeiedri** [comment]
We are aware of this problem as we've had problems with Google play for the last couple of weeksWell fix is as soon as possibleSent from my Samsung Galaxy smartphone.
-------- Original message --------From: XAMIR555 <notifications@github.com> Date: 5/17/19  00:01  (GMT+02:00) To: Chooloo/call_manage <call_manage@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Chooloo/call_manage] The [call_manage ] application does not appear when I click the google play store button (#12) Project Information

Repository-----------:Here
Project Name---------: call_manage
Publisher------------:  Chooloo
My GitHub account----:  Here

Expected behavior
When I click on the Google Play Store button, The Call-manage application should appear in the Google Play Store so that from where I install this application in my mobile
Actual behavior
When I click the Google Play Store button, the application does not appear further, but there is an error in which it is written (no app such found)
How to reproduce


Open github link on mobile


Click the Google Play Store button


Note the Bug


Operating system----: 9.0.0


Recording Of The Bug


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Chooloo/call_manage/issues/12?email_source=notifications\u0026email_token=AF574R7K4IHXAEMOQBGZ7XDPVXDTTA5CNFSM4HNQEYFKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUISPEQ",
"url": "https://github.com/Chooloo/call_manage/issues/12?email_source=notifications\u0026email_token=AF574R7K4IHXAEMOQBGZ7XDPVXDTTA5CNFSM4HNQEYFKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GUISPEQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by XAMIR555** [comment]
Thank you for your response

**Comment by XAMIR555** [comment]
thanks you sir

**Comment by roeiedri** [comment]
No Problemo
