### ISSUE TITLE
Koler V0.2.7 - Search button and the button that displays the interface to dial numbers turns blank after searching, and dialing a number

### ISSUE THREAD

**Issue by realrufans** [Chooloo/call_manage#5]
#### Expected behavior
I expected both  buttons to display their logo even after searching and dialing a number.

#### Actual behavior

Search button and the button that displays the interface to dial numbers turns blank after dialing, and searching a number.

#### How to reproduce
- launch Koler, then, locate the interface to press a number
- Type any number
- Click on dial button, then, end the call
- Click on search button
- Click on dial button, then, end the call again.
- Watch as the buttons turn blank
![Screenshot_20190515-132556.png](https://cdn.steemitimages.com/DQmRcwoa4z14fXzqcuUxoLEMLwc6RYMwfbNCpLE4CRzNDbP/Screenshot_20190515-132556.png)

##### Browser/App version:
Koler v0.27

##### Operating system:
Android 0

#### Recording Of The Bug

![MNML-May15-0154-1557925301930.gif](https://cdn.steemitimages.com/DQmU63ffoMScXey3RZxkgsR6N8Xma891UzDsgRfAYMSAFaG/MNML-May15-0154-1557925301930.gif)

**Comment by roeiedri** [comment]
We will fix these issues as soon as possiblethank you for contacting usSent from my Samsung Galaxy smartphone.
-------- Original message --------From: solomon stephen <notifications@github.com> Date: 5/15/19  16:09  (GMT+02:00) To: Chooloo/call_manage <call_manage@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Chooloo/call_manage] Koler V0.2.7 - Search button and the button that displays the interface to dial numbers turns blank after searching, and dialing a number (#5) Expected behavior
I expected both  buttons to display their logo even after searching and dialing a number.
Actual behavior
Search button and the button that displays the interface to dial numbers turns blank after dialing, and searching a number.
How to reproduce

launch Koler, then, locate the interface to press a number
Type any number
Click on dial button, then, end the call
Click on search button
Click on dial button, then, end the call again.
Watch as the buttons turn blank


Browser/App version:
Koler v0.27
Operating system:
Android 0
Recording Of The Bug


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Chooloo/call_manage/issues/5?email_source=notifications\u0026email_token=AF574R7VQLG65KS6R63EWX3PVQDP3A5CNFSM4HNDEGWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GT5ORYQ",
"url": "https://github.com/Chooloo/call_manage/issues/5?email_source=notifications\u0026email_token=AF574R7VQLG65KS6R63EWX3PVQDP3A5CNFSM4HNDEGWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GT5ORYQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by realrufans** [comment]
Welcome
