### ISSUE TITLE
Automatic night mode switching, following system condition

### ISSUE THREAD

**Issue by jumper047** [Chooloo/call_manage#51]
**Is your feature request related to a problem? Please describe.**
My phone switches from light to dark theme back and forth automatically. Most apps switching their theme, too, but Koler always stays with same theme
**Describe the solution you'd like**
I want Koler to became dark/ligth according to system's settings

**Comment by roeiedri** [comment]
Hey thank you for contacting us,
Unfortunately we currently don't support the app due to lack of money and
time.
Well do our best to push a new update with more features.
All we want is to be able to keep working on this and keep it free for
everyone to enjoy but currently its hard.
Thank you and we hope you still enjoy the app.

**Comment by jumper047** [comment]
I hope you (or someone else - it is open source:)) will implement it some time. Anyway, thx for your work!
