### ISSUE TITLE
dashes are ignored and numbers are not formatted

### ISSUE THREAD

**Issue by 532910** [Chooloo/call_manage#68]
It should be `+7 800 555-02-69`

![image](https://user-images.githubusercontent.com/14617699/84983147-d18e2b00-b140-11ea-9a6e-56e26cb4697d.png)

**Comment by 532910** [comment]
Same as in the Recents list.

**Comment by KhushrajRathod** [comment]
Should be a bug, not an enhancement. Calls fail if no dashes are shown as the country code is part of the number:  #58

**Comment by roeiedri** [comment]
It shouldn't be a bug, the number without the signs is the number the phone processes and can handle to make a call, it's an enhancement because it doesn't interrupt the flow of the app and meant only for user readability purposes
If call fails, it's not that and itll be great if u could report a bug is there is or check out the other issues and see if it's has already been reported
Im trying to do the best with the little time i have to try and support the app, it might take some time, i hope it's not too bad and u can still enjoy the app
@KhushrajRathod

**Comment by 532910** [comment]
This IS a bug, as a number MUST start with plus sign!

**Comment by 532910** [comment]
Right now it's completely unusable as I can't call any number from my phonebook.

**Comment by KhushrajRathod** [comment]
Hi @roeiedri, thanks for supporting the app. I believe this is a bug as I cannot dial any numbers in my address book atm, rendering the app effectively useless. Thanks again 👍

**Comment by KhushrajRathod** [comment]
@532910 Could you make this issue only about the dashes and follow the + issue? That way this can be an enhancement and that can be a bug
