### ISSUE TITLE
Long names are shown differently across screens

### ISSUE THREAD

**Issue by zhirzh** [Chooloo/call_manage#98]
**Describe the bug**
Long names are shown differently across screens:
- in Contacts & Recents screen, text is clipped without ellipsis
- in contact popup, text is wrapped
- in ongoing call screen, text is clipped with ellipsis but some part is also clipped on the left side

**Screenshots**
![3 - long name](https://user-images.githubusercontent.com/8132723/94451436-03953b80-01cc-11eb-9d3f-749ca146c45c.gif)

**Comment by roeiedri** [comment]
Nothing wrong with that, if youll make the name longer than it will be shown with dots in Contacts and Recents
Anyway what I did not is adding 3 line max limitation to the contact pop up and also fixed (i think :)) the third point you wrote with the text moving to the left in OngoingCall screen

**Comment by zhirzh** [comment]
What I am suggesting is that long name should be clipped the same way in all screens.

**Comment by roeiedri** [comment]
Yeah I understand but its like this for a reason
If the name would be clipped in all the screens than you'll not be able to see the full name anywhere
So I did change the name to be clipped in Contact and Recents as well but in contact pop up I just added 3 lines limitation
Because that's where you would want to see the full name
